# List of secrets checks to suppress
# Each suppression requires a justification. (Place in the 'description'.)
allow-rules:
  - id: allow-snakeoil-private-key
    description: snakeoil requires a private key
    path: /etc/ssl/private/ssl-cert-snakeoil.key
