---
name: Build and publish a Docker image

on:
  workflow_call:
    inputs:
      NOTEBOOK_TYPE:
        required: true
        type: string

env:
  IMAGE_PATH: ghcr.io/${{ github.repository }}-${{ inputs.NOTEBOOK_TYPE }}
  TARFILE_ARTIFACT: ${{ inputs.NOTEBOOK_TYPE }}-image-tarfile
  TARFILE_NAME: ${{ inputs.NOTEBOOK_TYPE }}-image.tar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.IMAGE_PATH }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}} # major.minor.patch
            type=semver,pattern={{major}}.{{minor}}

      - name: Build Docker image for scanning, but don't push to GHCR yet
        uses: docker/build-push-action@v6.4.0
        id: build
        with:
          context: .
          build-args: notebook_type=${{ inputs.NOTEBOOK_TYPE }}
          push: false
          load: true
          outputs: type=osi,dest=${{ env.TARFILE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Upload tarball for use by Trivy job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARFILE_NAME }}
          path: ${{ env.TARFILE_NAME }}

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      tarfile_artifact: ${{ env.TARFILE_NAME }}

  trivy-scan:
    needs: build
    uses: "./.github/workflows/trivy.yml"
    with:
      NOTEBOOK_TYPE: ${{ inputs.NOTEBOOK_TYPE }}
      SOURCE_TYPE: tar
      SOURCE_REF: ${{ needs.build.outputs.tarfile_artifact }}
      EXIT_CODE: 1

  push-image:
    needs: trivy-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download tar file
        id: tar-download
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TARFILE_NAME }}

      - name: Load image from tar
        run: docker load --input \
          ${{ steps.tar-download.outputs.download-path }}
          /${{ env.TARFILE_NAME }}

      - name: Push Docker image
        # Per https://docs.docker.com/build/ci/github-actions/test-before-push,
        # The image is built once [in the 'build' step],
        # and [this step uses] the internal cache from the [earlier] step.
        uses: docker/build-push-action@v6.4.0
        with:
          context: .
          build-args: notebook_type=${{ inputs.NOTEBOOK_TYPE }}
          push: true
          tags: ${{ needs.build.outputs.tags }}
          labels: ${{ needs.build.outputs.labels }}
...
