---
#
# This workflow builds a Docker image and passes it to Trivy for
# vulnerability scanning, only publishing it to ghrc.io if
# the scan passes.
#
name: Build and publish a Docker image

on:
  workflow_call:
    inputs:
      NOTEBOOK_TYPE:
        required: true
        type: string
      REF_TO_CHECKOUT:
        required: false
        type: string
        description: reference to checkout, e.g. a tag like v1.0.1.  Defaults to the branch/tag of the current event.
      TAGS:
        required: true
        type: string
        description: "comma delimited list of tags, e.g., 2.3.4, or main,1.0,1.0.1"

env:
  TARFILE_NAME: ${{ inputs.NOTEBOOK_TYPE }}-image.tar

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.REF_TO_CHECKOUT }}

      - name: Build Docker image for scanning, but don't push to ghcr.io yet
        uses: docker/build-push-action@v6.4.0
        with:
          context: .
          build-args: notebook_type=${{ inputs.NOTEBOOK_TYPE }}
          push: false
          outputs: type=tar,dest=${{ env.TARFILE_NAME }}

      - name: Upload tarball for use by Trivy job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARFILE_NAME }}
          path: ${{ env.TARFILE_NAME }}

    outputs:
      tarfile_artifact: ${{ env.TARFILE_NAME }}

  trivy-scan:
    needs: tests
    uses: "./.github/workflows/trivy.yml"
    with:
      NOTEBOOK_TYPE: ${{ inputs.NOTEBOOK_TYPE }}
      SOURCE_TYPE: tar
      IMAGE_NAME: image-name
      TARFILE_NAME: ${{ needs.tests.outputs.tarfile_artifact }}
      EXIT_CODE: 1

  push-image:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    needs: [tests, trivy-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.REF_TO_CHECKOUT }}

      - name: Prepend image references with repo' names to produce image references
        id: image_references
        run: |
          # convert repo' name to lower case to be used as a Docker name
          repo_name=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')-${{ inputs.NOTEBOOK_TYPE }}
          # comma separated list of tags
          tag_list=${{ inputs.TAGS }}
          # prepend each tag with repo name, e.g., "tag1"->"reponame:tag1"; "tag1,tag2"->"reponame:tag1,reponame:tag2"
          image_references=$repo_name:${tag_list//,/,$repo_name:}
          echo "image_references=$image_references" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.4.0
        with:
          build-args: notebook_type=${{ inputs.NOTEBOOK_TYPE }}
          context: .
          push: true
          tags: ${{ env.image_references }}
...
