---
name: Run tests and conditionally build container

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Static Analysis
        uses: pre-commit/action@v3.0.0

      - name: Build Docker Image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          build-args: notebook_type=jupyter

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest tests/ -s -v

  trivy:
    name: Trivy-vulnerability-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: Git Repository

  docker-build-push-jupyter:
    if: ${{ github.event_name == 'push' }}
    needs: [tests, trivy]
    uses: "./.github/workflows/docker_build_push.yml"
    secrets: inherit
    with:
      NOTEBOOK_TYPE: jupyter

  docker-build-push-rstudio:
    if: ${{ github.event_name == 'push' }}
    needs: [tests, trivy]
    uses: "./.github/workflows/docker_build_push.yml"
    secrets: inherit
    with:
      NOTEBOOK_TYPE: rstudio
...
