---
#
# This workflow scans the published container images
# for new vulnerabilities daily, publishing findings.
# Findings will be associated with the 'main' branch
# of the repo' in the GitHub Security tab.
#
name: Trivy Periodic Image Scan

on:
  schedule:
    # run daily
    - cron: "0 0 * * *"

jobs:
  lower-case:
    runs-on: ubuntu-latest
    name: lower-case
    steps:
      - name: Ensure repo' name is lower case
        id: repo
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ github.repository }}
    outputs:
      lowercase: ${{ steps.repo.outputs.lowercase }}

  trivy-matrix:
    name: trivy-${{ matrix.notebook_type }}
    needs: lower-case
    strategy:
      matrix:
        notebook_type:
          - jupyter
          - rstudio
    uses: "./.github/workflows/trivy.yml"
    with:
      NOTEBOOK_TYPE: ${{ matrix.notebook_type }}
      SOURCE_TYPE: image
      IMAGE_NAME: ghcr.io/${{ needs.lower-case.outputs.lowercase
            }}-${{ matrix.notebook_type }}:main
...
