---
name: Trivy Periodic Image Scan

on:
  schedule:
    # at the top of each hour (for testing)
    - cron: "0 * * * *"
    # TODO change to daily
    # - cron: "0 0 * * *"

jobs:
  trivy:
    name: ${{ matrix.notebook_type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook_type:
          - jupyter
          - rstudio
    uses: "./.github/workflows/trivy.yml"
    secrets: inherit
    with:
      NOTEBOOK_TYPE: ${{ matrix.notebook_type }}
      IMAGE_REF: ghcr.io/${{ github.repository }}-\
        ${{ matrix.notebook_type }}:main
...
