---
name: Trivy Periodic Image Scan

on:
  schedule:
    # at the top of each hour (for testing)
    - cron: "0 * * * *"
    # TODO change to daily
    # - cron: "0 0 * * *"

jobs:
  trivy-matrix:
    name: ${{ matrix.notebook_type }}
    strategy:
      matrix:
        notebook_type:
          - jupyter
          - rstudio
    uses: "./.github/workflows/trivy.yml"
    with:
      NOTEBOOK_TYPE: ${{ matrix.notebook_type }}
      SOURCE_TYPE: image
      IMAGE_NAME: ghcr.io/${{ github.repository }}-\
            ${{ matrix.notebook_type }}:main
...
